### PR TITLE
Open source updates

### PR DESCRIPTION
**Pull request by kford55**
Updated license and other files necessary for our open source requirements. I also updated the package names to match our generic codelab package names

### CODE REVIEW

**Comment by kford55** [comment]
@pfmaggi @CesarValiente If you can pull this down and just verify it works and builds on your machine. I had a slight issue originally after renaming package names that I just want to confirm I didn't fix locally only.

**Review by pfmaggi — APPROVED** [review]
LGTM
just a couple of nits
- gradlew is not executable
- the layout for windowmanager/mainactivity has a warning for the last view because it has no constraints. This causes `./gradlew build` to fail.
We can address this later on:
```
    <View
        android:id="@+id/device_feature"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="@android:color/holo_red_dark"
        android:visibility="gone"
        tools:ignore="MissingConstraints" />
```

**Comment by CesarValiente** [comment]
LGTM too, tested all apps and they all work as expected.
And just confirming too what Pietro has said before, although on windows `gradlew.bat` works well.

**Comment by kford55** [comment]
Updated the WM version to alpha 03!

**Comment by pfmaggi** [comment]
LGTM :shipit:

**Comment by CesarValiente** [comment]
LGTM too!

**Pull request merged**
