### PR TITLE
Replace Kotlin Synthetic with ViewBinding

### PR DESCRIPTION
**Pull request by pfmaggi**
- Add ViewBinding
- Add newline at the end of files
- Remove Buildtools from build.gradle
- Update dependencies
- Remove Kotlin Synthetic
- Update to latest Kotlin version
- Use with in place of repeating binding.dropEditText in Drop project

### CODE REVIEW

**Comment by CesarValiente** [comment]
Thanks for the work Pietro! 😉
LGTM! but can you please rebase your PR to use the latest `main` branch changes? Thanks!

**Review by CesarValiente — CHANGES_REQUESTED** [review]
Thanks for the work Pietro! 😉
LGTM! but can you please rebase your PR to use the latest main branch changes? Thanks!

**Comment by CesarValiente** [comment]
Thanks for addressing the requested change Pietro. I will merge it 🚀

**Comment by pfmaggi** [comment]
Rebased on top of your last update.

**Pull request merged**
